# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc4144f6945b90bd848e143f9167e36d48d9592e0a7a8b5f62930bf0861885aaa814f15e7c0938bea22dd92886c161814f2d1feb3e10af7df42f24f27c2c364e

test:
  secret_key_base: b1d535b54ce2df94e9a652feae4622d1adc22f6e5cd00a2a4a4fd3eef1123b7b10a906b392d57cfc4ca19d74c7671cf229c62e01fee024b482a6a28864c4e118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
